### ISSUE TITLE
missing in docs - how to run task on different workers ? how to use broker?

### ISSUE THREAD

**Issue by alekibango** [socketubs/carotte#3]
Just after few minutes of playing with carotte i must say i like it.

But docs should really have examples for those use cases:

When  i am running carrotte on different addresses like this:
 ```  carotte worker --app app:my_app --bind=inproc://tmp/aa``` 
how should i call my  tasks?

How to run tasks on different workers **with** and **without** broker?  How to run broker?

**Comment by socketubs** [comment]
Hi @alekibango ,

Worker and client (process which send tasks) can't use `inproc` cause they are two different processes.
You must use real socket of unix socket, like that:
```carotte worker --app app:my_app --bind=ipc:///tmp/carotte```

And from any python code:
```
from carotte import Client
c = Client(worker="ipc:///tmp/carotte")
c.run_task('my_task')
```

Or if you use a worker on a different machine, you can use a tcp socket instead of `ipc`.

You don't have broker. Carotte is "lightweight", worker is the broker. This is why you can't have multiple worker.
Carotte is designed to be fast to deploy, easy to use, no magic and not so far from Celery usage.

Is it ok for you ? :smile:

**Comment by alekibango** [comment]
hi, yes, this is what i asked about, thanks for answer.  I should have  known inproc/ipc and tcp differences already, but it was long time since i have seen the zmq guide... Thanks.

I think that it would be very nice to support at least some kind of brokers and proxies. 
I was able in 5 minutes to write simple broker using example from zguide, connecting few workers  to it, with minimal change in carotte.  Everything 'worked', except that routing was pseudorandom --  asking random (wrong) workers for status, when i had more of them. I need to try again with better routing.

If i will use carotte for my project, i will probably need brokers and clusters, [with interbroker routing](http://zguide.zeromq.org/py:all#Worked-Example-Inter-Broker-Routing)... 
I have too many machines/processes to let them talk to each other all the time. And I really need brokers to make  load balancing for my workers and groups of workers, at least for some of my jobs.  

I will do some experiments to see how to make it work right.

**Comment by socketubs** [comment]
hi @alekibango ,

The problem with broker is that you'll need a database or something were tasks results are stored. This is why today carotte does not support multiple worker/brokers.
Before if you root a job to a specific worker, when your client need task result, how can you know which worker have stored the result ?

Or you need a main server that dispatch to workers and this server store results ? Maybe.
But it's interesting that you want to use carotte in a bigger environment.
My first try to build carotte was for an easy deploy instead of Celery/RabbitMQ, but I am open to any contribution.

:smile:
